name: event_driven_gcp_snow
version: 1.0.0
config-version: 2
profile: event_driven_gcp_snow
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  event_driven_gcp_snow:
    +materialized: view
