event_driven_gcp_snow:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: BOWOYMW-EP41167
      user: DEVLEO1984
      role: ROLE_TRANSFORMER
      warehouse: WH_TRANSFORM_S
      database: ANALYTICS_DEV
      schema: GOLD
      threads: 4
    qa:
      type: snowflake
      account: BOWOYMW-EP41167
      user: DEVLEO1984
      role: ROLE_TRANSFORMER
      warehouse: WH_TRANSFORM_S
      database: ANALYTICS_QA
      schema: GOLD
      threads: 4
    prod:
      type: snowflake
      account: BOWOYMW-EP41167
      user: DEVLEO1984
      role: ROLE_TRANSFORMER
      warehouse: WH_TRANSFORM_S
      database: ANALYTICS_PROD
      schema: GOLD
      threads: 4
      
