event_driven_gcp_snow:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ROLE_TRANSFORMER
      warehouse: WH_TRANSFORM_S
      database: ANALYTICS_DEV
      schema: GOLD
      threads: 8
